image: golang:latest

variables:
  REPO_NAME: github.com/blk-io/crux

# The problem is that to be able to use go get, one needs to put
# the repository in the $GOPATH. So for example if your gitlab domain
# is gitlab.com, and that your repository is namespace/project, and
# the default GOPATH being /go, then you'd need to have your
# repository in /go/src/gitlab.com/namespace/project
# Thus, making a symbolic link corrects this.
before_script:
  - apt-get update -qq && apt-get install -y -qq libdb-dev libpthread-stubs0-dev # This is hopefully temporary until we completely remove BerkeleyDB.
  - mkdir -p $GOPATH/src/$(dirname $REPO_NAME)
  - ln -svf $CI_PROJECT_DIR $GOPATH/src/$REPO_NAME
  - cd $GOPATH/src/$REPO_NAME
  - go get ./...
  - make setup

stages:
    - build
    - test

format:
    stage: test
    script:
      - go fmt $(go list ./... | grep -v /vendor/)
      - go vet $(go list ./... | grep -v /vendor/)
      - make test

compile:
    stage: build
    script:
      - make build
    artifacts:
      paths:
        - crux

code_coverage:
    stage: test
    script:
      - rm -f $GOPATH/cover/*.out $GOPATH/cover/all.merged
      - mkdir -p $GOPATH/cover
      - make cover

